### ISSUE TITLE
[question] How to add the directory of `vcvarsall.bat` into env `PATH` in GitHub Actions?

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/cmake-conan#465]
### Problem Description

Is it possible to add the directory of `vcvarsall.bat` into env `PATH` in GitHub Actions? If it is possible, then we might be able to test the situations which use **MSVC** compilers with the following CMake generators:

* **NMake Makefiles**
* **Ninja**
* **Ninja Multi-Config**

by calling `vcvarsall.bat` in the `tests.py`.

Does anyone or Conan Team know how to implement this?

**Comment by hwhsu1231** [comment]
I think I found the implementation to do so. 

* Link: https://github.com/orgs/community/discussions/26887#discussioncomment-4302176

```yaml
- name: Append the directory of 'vcvarsall.bat' to PATH environment variable
  uses: myci-actions/export-env-var-powershell@1
  with:
    name: PATH
    value: $env:PATH;C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build
```
